-- Create parent table first (referenced by job_listings.scan_id)
CREATE TABLE scans
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_run        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    scan_count      INTEGER                                 NOT NULL,
    service_scanned VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_scans PRIMARY KEY (id)
);

CREATE TABLE job_listings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    summary          TEXT,
    company_name     VARCHAR(255),
    job_location     VARCHAR(255),
    details_page_url TEXT,
    company_page_url TEXT,
    salary           VARCHAR(255),
    employment_type  VARCHAR(255),
    workplace_types  VARCHAR(255),
    posted_date      VARCHAR(255),
    easy_apply       BOOLEAN,
    dice_id          VARCHAR(255),
    applied          BOOLEAN                                 NOT NULL,
    rejected         BOOLEAN                                 NOT NULL,
    scan_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_job_listings PRIMARY KEY (id)
);

ALTER TABLE job_listings
    ADD CONSTRAINT fk_job_listings_scan
        FOREIGN KEY (scan_id) REFERENCES scans (id);